# Generated by Django 5.2.7 on 2026-06-28 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('dominant_color', models.CharField(max_length=100)),
                ('analysis_json', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('CASUAL', 'Casual'), ('OFFICE', 'Office'), ('PARTY', 'Party'), ('DATE_NIGHT', 'Date Night'), ('COLLEGE', 'College'), ('VACATION', 'Vacation'), ('WINTER', 'Winter'), ('SUMMER', 'Summer'), ('TRADITIONAL', 'Traditional')], max_length=30)),
                ('user_prompt', models.TextField(blank=True)),
                ('recommendation_json', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_session', to='stylist.clothinganalysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_image', models.ImageField(upload_to='generated/')),
                ('option_number', models.PositiveSmallIntegerField()),
                ('generation_prompt', models.TextField()),
                ('style_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='stylist.stylesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clothinganalysis',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='stylist.upload'),
        ),
    ]
